name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Test
        run: make test
