name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Install swift-format
        run: brew install swift-format

      - name: lint
        run: make lint

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4

  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: build
        run: make clean-build

      - name: test
        run: make ci-test
