name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Install swift-format
        run: brew install swift-format

      - name: lint
        run: make lint

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4

  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install http-server
        run: npm install -g http-server

      - name: start test-server
        run: make server && sleep 2 && cat server.log

      - name: test
        run: make test

      - name: check server logs
        run: cat server.log
