name: Lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Tap
        run: brew tap pointfreeco/formulae

      - name: Install
        run: brew install Formulae/swift-format@5.4

      - name: Lint files
        run: make lint
